# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [1]:
# your code here
import pandas as pd

# Leer el archivo CSV en un DataFrame
tic_tac_toe_df = pd.read_csv('tic-tac-toe.csv')

# Mostrar las primeras filas del dataset
print("Primeras filas del dataset:")
print(tic_tac_toe_df.head())


Primeras filas del dataset:
  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True


In [2]:
# Reemplazar valores categóricos por números
tic_tac_toe_numeric = tic_tac_toe_df.replace({
    'x': 1,  # Jugador X
    'o': -1, # Jugador O
    'b': 0,  # Celda vacía
    True: 1, # X gana
    False: 0 # X no gana
})

# Mostrar las primeras filas del dataset convertido
print("\nDataset con valores numéricos:")
print(tic_tac_toe_numeric.head())



Dataset con valores numéricos:
   TL  TM  TR  ML  MM  MR  BL  BM  BR  class
0   1   1   1   1  -1  -1   1  -1  -1      1
1   1   1   1   1  -1  -1  -1   1  -1      1
2   1   1   1   1  -1  -1  -1  -1   1      1
3   1   1   1   1  -1  -1  -1   0   0      1
4   1   1   1   1  -1  -1   0  -1   0      1


/var/folders/ln/h2lpkllx5fl21m8307tnfsdc0000gn/T/ipykernel_50363/2114337433.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  tic_tac_toe_numeric = tic_tac_toe_df.replace({


In [3]:
# Separar entradas (X) y salidas (y)
X = tic_tac_toe_numeric.iloc[:, :-1]  # Todas las columnas menos la última son las entradas
y = tic_tac_toe_numeric.iloc[:, -1]   # La última columna es la salida

# Mostrar las primeras filas de las entradas y salidas
print("\nEntradas (X):")
print(X.head())

print("\nSalidas (y):")
print(y.head())



Entradas (X):
   TL  TM  TR  ML  MM  MR  BL  BM  BR
0   1   1   1   1  -1  -1   1  -1  -1
1   1   1   1   1  -1  -1  -1   1  -1
2   1   1   1   1  -1  -1  -1  -1   1
3   1   1   1   1  -1  -1  -1   0   0
4   1   1   1   1  -1  -1   0  -1   0

Salidas (y):
0    1
1    1
2    1
3    1
4    1
Name: class, dtype: int64


In [4]:
from sklearn.preprocessing import MinMaxScaler

# Normalizar las entradas
scaler = MinMaxScaler(feature_range=(-1, 1))
X_normalized = scaler.fit_transform(X)

# Mostrar las primeras filas normalizadas
print("\nEntradas normalizadas:")
print(pd.DataFrame(X_normalized, columns=X.columns).head())



Entradas normalizadas:
    TL   TM   TR   ML   MM   MR   BL   BM   BR
0  1.0  1.0  1.0  1.0 -1.0 -1.0  1.0 -1.0 -1.0
1  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0  1.0 -1.0
2  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0  1.0
3  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0  0.0  0.0
4  1.0  1.0  1.0  1.0 -1.0 -1.0  0.0 -1.0  0.0


## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [5]:
# your code here

from sklearn.model_selection import train_test_split

# Dividir los datos en conjuntos de entrenamiento (80%) y prueba (20%)
X_train, X_test, y_train, y_test = train_test_split(X_normalized, y, test_size=0.2, random_state=42)

# Mostrar el tamaño de los conjuntos
print("\nTamaños de los conjuntos:")
print(f"Entrenamiento: {len(X_train)} ejemplos, Prueba: {len(X_test)} ejemplos")



Tamaños de los conjuntos:
Entrenamiento: 766 ejemplos, Prueba: 192 ejemplos


In [6]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Crear un modelo secuencial
model = Sequential()

# Agregar capas al modelo
model.add(Dense(64, activation='relu', input_shape=(X_train.shape[1],)))  # Capa oculta 1
model.add(Dense(32, activation='relu'))  # Capa oculta 2
model.add(Dense(2, activation='softmax'))  # Capa de salida (2 clases: X gana o no)

# Mostrar un resumen del modelo
print("\nResumen del modelo:")
model.summary()


2024-12-02 15:51:00.795565: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.



Resumen del modelo:


/Users/kikegarciabello/anaconda3/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 2)              │            66 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,786 (10.88 KB)

 Trainable params: 2,786 (10.88 KB)

 Non-trainable params: 0 (0.00 B)

In [7]:
# Compilar el modelo
model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy', 
              metrics=['accuracy'])

print("\nModelo compilado.")



Modelo compilado.


In [8]:
# Entrenar el modelo
history = model.fit(X_train, y_train, epochs=50, batch_size=32, verbose=1)

print("\nModelo entrenado.")


Epoch 1/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6452 - loss: 0.6539
Epoch 2/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7232 - loss: 0.5694
Epoch 3/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7771 - loss: 0.5207
Epoch 4/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7886 - loss: 0.4808
Epoch 5/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8152 - loss: 0.4414
Epoch 6/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8368 - loss: 0.4127
Epoch 7/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8436 - loss: 0.3717
Epoch 8/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9081 - loss: 0.3116
Epoch 9/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9369 - loss: 0.2659
Epoch 10/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9637 - loss: 0.2373  
Epoch 11/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9708 - loss: 0.1807
Epoch 12/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9901 - 

In [9]:
# Evaluar el modelo en los datos de prueba
test_loss, test_accuracy = model.evaluate(X_test, y_test)

print(f"\nPrecisión en los datos de prueba: {test_accuracy:.2f}")


6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9731 - loss: 0.0449  

Precisión en los datos de prueba: 0.98


In [11]:
# Guardar el modelo
model.save('tic-tac-toe.keras')
print("\nModelo guardado como 'tic-tac-toe.keras'.")


Modelo guardado como 'tic-tac-toe.keras'.


## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [13]:
# your code here
from tensorflow.keras.models import load_model

# Cargar el modelo guardado
model = load_model('tic-tac-toe.keras')

# Confirmar que el modelo se ha cargado
print("\nModelo cargado exitosamente.")
model.summary()



Modelo cargado exitosamente.


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 2)              │            66 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 8,360 (32.66 KB)

 Trainable params: 2,786 (10.88 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 5,574 (21.78 KB)

In [14]:
import numpy as np

# Seleccionar índices aleatorios
random_indices = np.random.choice(len(X_test), size=5, replace=False)

# Obtener las muestras de prueba seleccionadas
X_sample = X_test[random_indices]
y_sample = y_test.iloc[random_indices]

print("\nFilas aleatorias seleccionadas:")
print(X_sample)



Filas aleatorias seleccionadas:
[[ 0. -1. -1.  0.  0.  0.  1.  1.  1.]
 [-1.  1. -1.  1.  1.  1.  0.  0. -1.]
 [ 1.  1.  0. -1. -1. -1. -1.  1.  1.]
 [ 1.  0.  0.  1. -1. -1.  1.  0.  0.]
 [-1. -1. -1.  1.  0.  0.  1.  0.  1.]]


In [15]:
# Hacer predicciones
predictions = model.predict(X_sample)

# Convertir las probabilidades en etiquetas (clase más probable)
predicted_classes = np.argmax(predictions, axis=1)

print("\nPredicciones:")
print(predicted_classes)
print("\nEtiquetas reales:")
print(y_sample.values)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

Predicciones:
[1 1 0 1 0]

Etiquetas reales:
[1 1 0 1 0]


In [16]:
# Comparar predicciones con las etiquetas reales
correct_predictions = predicted_classes == y_sample.values
print("\nPredicciones correctas (True/False):")
print(correct_predictions)

# Mostrar el porcentaje de aciertos
accuracy = np.mean(correct_predictions) * 100
print(f"\nPrecisión en las muestras seleccionadas: {accuracy:.2f}%")



Predicciones correctas (True/False):
[ True  True  True  True  True]

Precisión en las muestras seleccionadas: 100.00%


## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [17]:
# your code here
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Crear un modelo con más capas
model = Sequential()

# Capa oculta 1
model.add(Dense(128, activation='relu', input_shape=(X_train.shape[1],)))  # Más neuronas
# Capa oculta 2
model.add(Dense(64, activation='relu'))  # Mantener capas intermedias
# Capa oculta 3
model.add(Dense(32, activation='relu'))  # Agregar una capa adicional
# Capa de salida
model.add(Dense(2, activation='softmax'))

# Mostrar el resumen del modelo
print("\nModelo con más capas:")
model.summary()



Modelo con más capas:


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 128)            │         1,280 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 2)              │            66 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11,682 (45.63 KB)

 Trainable params: 11,682 (45.63 KB)

 Non-trainable params: 0 (0.00 B)

In [18]:
from tensorflow.keras.optimizers import Adam

# Crear un optimizador Adam con una tasa de aprendizaje personalizada
custom_optimizer = Adam(learning_rate=0.001)  # Tasa de aprendizaje ajustada

# Compilar el modelo
model.compile(optimizer=custom_optimizer, 
              loss='sparse_categorical_crossentropy', 
              metrics=['accuracy'])

print("\nModelo compilado con una tasa de aprendizaje ajustada.")



Modelo compilado con una tasa de aprendizaje ajustada.


In [19]:
# Entrenar el modelo con más épocas
history = model.fit(X_train, y_train, epochs=100, batch_size=32, verbose=1)

print("\nModelo entrenado con más épocas.")


Epoch 1/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6486 - loss: 0.6490
Epoch 2/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7537 - loss: 0.5212
Epoch 3/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8169 - loss: 0.4327
Epoch 4/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8731 - loss: 0.3430
Epoch 5/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9567 - loss: 0.2404
Epoch 6/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9787 - loss: 0.1541
Epoch 7/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9886 - loss: 0.0841 
Epoch 8/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9967 - loss: 0.0450
Epoch 9/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9971 - loss: 0.0305
Epoch 10/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0163
Epoch 11/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0113
Epoch 12/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy

In [20]:
# Evaluar el modelo en los datos de prueba
test_loss, test_accuracy = model.evaluate(X_test, y_test)

print(f"\nPrecisión del modelo mejorado en los datos de prueba: {test_accuracy:.2f}")
print(f"Pérdida del modelo mejorado en los datos de prueba: {test_loss:.4f}")


6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9950 - loss: 0.0084  

Precisión del modelo mejorado en los datos de prueba: 0.99
Pérdida del modelo mejorado en los datos de prueba: 0.0107


In [21]:
# Guardar el modelo mejorado
model.save('tic-tac-toe-improved.keras')
print("\nModelo mejorado guardado como 'tic-tac-toe-improved.keras'.")



Modelo mejorado guardado como 'tic-tac-toe-improved.keras'.


**Which approach(es) did you find helpful to improve your model performance?**

In [ ]:
# your answer heree

# add more layers to the neuron is the easiest approach. It is easy to implement but you have to be careful with the number of layers
#adjust the learning rate is easy but could be dangerous
#rise the number of epochs 